### ISSUE TITLE
В корзине нельзя заказать 

### ISSUE THREAD

**Issue by camorazrushimoe** [digitalshop24/dremteam#11]
При клике "Заказать" в корзине. Ничего не происходит:
![image](https://cloud.githubusercontent.com/assets/8914398/16259460/81cadc32-386b-11e6-99c4-270f20a6fd27.png)

**Comment by gitwhatislove** [comment]
Там, три страницы, но их наверное в сущности нужно вынести и при клике перход к каждой странице. Я настрою сегодня гугл таблицу

**Comment by gitwhatislove** [comment]
Плюс нужно, что бы id моделей или ссылка на них закидывалась в какой-нибудь input.Нужно будет списать, обсудить это
