### ISSUE TITLE
На странице модели нет информации о этой модели

### ISSUE THREAD

**Issue by camorazrushimoe** [digitalshop24/dremteam#12]
на странице модели, должна быть инфа о модели:
![image](https://cloud.githubusercontent.com/assets/8914398/16259569/f3f78e7c-386b-11e6-8451-aa15a838b67c.png)

**Comment by savushkin-yauheni** [comment]
отпиши сюда у какого типа staffa что должно быть.
т.к. это чувак скорее всего бармен или еще кто. поэтому ничего нет.
т.е. по пунктам:
у барменов тото и тото. и т.д.

**Comment by camorazrushimoe** [comment]
@yuliyakislach надо решить какую инфу будем выводить на карточке товара. Для всех типов стафа надо выводить поле описание. Но для моделей у нас были и дополнительные параметры, рост, цвет волос и т.п. Надо перечислить какие поля выводим и перевести таск  на Женю. 

@candalik а с доп картинками что нетак? по идее должен быть слайдер под фоткой. Типо такого:
![image](https://cloud.githubusercontent.com/assets/8914398/16275711/dea9bd9a-38b3-11e6-98cd-e1b9ac6347d0.png)
