### ISSUE TITLE
еще мобильники

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/dremteam#14]
По вертикали отцентрировать
![htnxijfcavs](https://cloud.githubusercontent.com/assets/18350195/16261386/028c78f0-3874-11e6-8dde-a539bef08b5f.jpg)
Главная
![f_o4hbumuaw](https://cloud.githubusercontent.com/assets/18350195/16261392/05bad3a0-3874-11e6-920e-2c67db050067.jpg)

**Comment by gitwhatislove** [comment]
первую правку не понял, что там не так?
