### ISSUE TITLE
Увеличить элементы

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/dremteam#15]
**На мобильниках, для образца dt-agency.ru**

![z54eeq7-qvc](https://cloud.githubusercontent.com/assets/18350195/16304920/46bc25e2-3960-11e6-8347-1cca26be31b6.jpg)
![12k5suihco0](https://cloud.githubusercontent.com/assets/18350195/16304922/476b8500-3960-11e6-9a6d-526c269d0848.jpg)

**Comment by gitwhatislove** [comment]
у меня все на мобильниках нормально, я не знаю, как это пофиксить((
