### ISSUE TITLE
Фотографы и прочие

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/dremteam#16]
![2016-06-24 15 04 08](https://cloud.githubusercontent.com/assets/18350195/16337398/cf8fe49a-3a1d-11e6-8a76-4474f130c792.png)

**Comment by gitwhatislove** [comment]
Куда ведет кнопка портфолио?!

**Comment by yuliyakislach** [comment]
на карточку фотографа, они такие же как и у моделей
