### ISSUE TITLE
Юлины правки по верстке.

### ISSUE THREAD

**Issue by gitwhatislove** [digitalshop24/dremteam#2]
https://docs.google.com/document/d/1F6Y3j4warAO6ussTvdCOg10uZNElfPwM6mHnyH61axk/edit

**Comment by yuliyakislach** [comment]
http://dt-agency.ru/#/order добавить необязательные поля форме отправки заказа
**Имя
Телефон
Email**
**Выпадающий список “Вид мероприятия”:**  
Выставка, Встреча гостей, Показ, Съемка фото, Съемка видео, Другое
**Поле текстовое “Количество часов” 
Выпадающий список “Доп. услуги”:** 
Пошив/Аренда одежды для персонала, Трансфер, Другое
**Текстовое поле “Ваш комментарий”**

**Comment by yuliyakislach** [comment]
Добавить текстовое поле над “Выбранный персонал” для размещения акций (текст или картинка)
Например, “Закажи Модель и получи услуги супервайзера в подарок!”
![image](https://cloud.githubusercontent.com/assets/18350195/15888486/551bd3da-2d67-11e6-8128-c98255337021.png)

**Comment by yuliyakislach** [comment]
http://dt-agency.ru/ 
Главный слайдер вместе с листалкой уместить в 1 экран

**Comment by yuliyakislach** [comment]
заходя на страницу модели при желании возврата к основному списку- выкидывает в самое начало и ты снова вынужден пролистывать всех - исправить

**Comment by yuliyakislach** [comment]
Исправить орфографические ошибки

Добавить букву  “агенством” на главной http://dt-agency.ru/ 
Выбранный персонал http://dt-agency.ru/#/order
Вернуться к каталогу - на страницах модели http://dt-agency.ru/#/catalog/10
Самостоятельно http://dt-agency.ru/#/

**Comment by yuliyakislach** [comment]
заменить мужчины и женщины на парни и девушки в фильтре
http://dt-agency.ru/#/catalog, раздел Модели

**Comment by yuliyakislach** [comment]
моделей в каталоге размещаем так (добавить пару пикселей между карточками, выводить имя и личный номер)
![image](https://cloud.githubusercontent.com/assets/18350195/15889333/20a8b326-2d6b-11e6-8227-0f122d9461a4.png)
Добавить постраничную пагинацию

**Comment by yuliyakislach** [comment]
Попапы для заказа и настроить Google таблицы 
- для форм заказа стаффа (с дом полями)
- для "Подобрать персонал" (со старого сайта)

**Comment by yuliyakislach** [comment]
Черный шрифт в шапке каталога
![2016-06-22 11 39 14](https://cloud.githubusercontent.com/assets/18350195/16223209/e1b29a94-37a4-11e6-8a86-6bc56372753d.png)

**Comment by yuliyakislach** [comment]
В корзине
![2016-06-22 11 41 40](https://cloud.githubusercontent.com/assets/18350195/16223259/14b9942e-37a5-11e6-8870-01968e120a88.png)

**Comment by yuliyakislach** [comment]
Прикрепить
![2016-06-22 11 47 35](https://cloud.githubusercontent.com/assets/18350195/16223443/e93f08e6-37a5-11e6-8a4e-30fd383c0a8b.png)
