### ISSUE TITLE
Кейтринг

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/dremteam#32]
Добавить в каталог "Кейтринг" (после стилисты)
Название Кейтринг  
Ключ для API keytring
![2016-07-19 14 26 51](https://cloud.githubusercontent.com/assets/18350195/16948266/673c74a0-4dbc-11e6-87b4-884aef97fe9a.png)

Добавить в каталог Staff    (после кейтринг)
Ключ для API  staff

**Comment by gitwhatislove** [comment]
Фильт пока не работает

**Comment by gitwhatislove** [comment]
- баг с отображением
