### ISSUE TITLE
Персонал для мероприятий

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/dremteam#48]
1
http://dt-agency.ru/system/photos/photos/000/000/082/medium/image%2810%29.jpeg
http://dt-agency.ru/person/16
2
http://dt-agency.ru/system/staffs/photos/000/000/006/medium/2_%D1%84%D0%BE%D1%82%D0%BE_-_%D0%BF%D0%B5%D1%80%D1%81%D0%BE%D0%BD%D0%B0%D0%BB_%D0%B4%D0%BB%D1%8F_%D0%BC%D0%B5%D1%80%D0%BE%D0%BF%D1%80%D0%B8%D1%82%D1%8F%D0%B8%D0%B9.jpeg
http://dt-agency.ru/person/22
3
http://dt-agency.ru/system/photos/photos/000/000/114/medium/image%282%29.jpeg
http://dt-agency.ru/person/22
4
http://dt-agency.ru/system/staffs/photos/000/000/019/medium/image.jpeg
http://dt-agency.ru/person/19

**Comment by gitwhatislove** [comment]
Захардкодить на главной
