### ISSUE TITLE
Фильтр

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/dremteam#56]
![2016-07-27 14 33 22](https://cloud.githubusercontent.com/assets/18350195/17173982/cd6142f6-5406-11e6-9cad-33a89db5d0bc.png)
Заметь цвет на желтый как кнопки
На 13 мониторах прыгает фильтр волос вниз

**Comment by yuliyakislach** [comment]
![2016-07-27 14 33 22](https://cloud.githubusercontent.com/assets/18350195/17173982/cd6142f6-5406-11e6-9cad-33a89db5d0bc.png)
Заметь цвет на желтый как кнопки
На 13 мониторах прыгает фильтр волос вниз

**Comment by yuliyakislach** [comment]
Переверстать

**Comment by gitwhatislove** [comment]
3 Я хз что делать с волосами, может их опустить вниз и центрировать, они просто не влазят(

**Comment by gitwhatislove** [comment]
dremteam-staging.dshop24.by все тут
