### ISSUE TITLE
Пагинация

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/dremteam#57]
Цифровая пагинация
3 строки на каждой страние
Возврат с карточки на страницу, откуда зашел

**Comment by gitwhatislove** [comment]
dremteam-staging.dshop24.by все тут

**Comment by yuliyakislach** [comment]
что с последним пунктом?

**Comment by yuliyakislach** [comment]
если я на 3й странице смотрю карточку - возвращается на нулевую.
сейчас вообще каталог сломался
