### ISSUE TITLE
Наши звезды

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/dremteam#58]
Добавить в модели над полом, выделить
![2016-07-27 15 23 23](https://cloud.githubusercontent.com/assets/18350195/17174927/86759ae8-540d-11e6-93a2-5a58fef925cb.png)

**Comment by gitwhatislove** [comment]
Добавь хотя бы одну звезду, потестить

**Comment by gitwhatislove** [comment]
id?)

**Comment by yuliyakislach** [comment]
16
