### ISSUE TITLE
Правки 2.0

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/dremteam#6]
![img_0321](https://cloud.githubusercontent.com/assets/18350195/16259809/0500fe50-386d-11e6-9aa7-4887f5f5d01d.PNG)

**Comment by yuliyakislach** [comment]
Кнопка после добавления в корзину
![2016-06-22 15 06 17](https://cloud.githubusercontent.com/assets/18350195/16228771/aafb1d10-37c1-11e6-8ce9-506321cd6aeb.png)

**Comment by yuliyakislach** [comment]
![img_0321](https://cloud.githubusercontent.com/assets/18350195/16259779/dce68ab6-386c-11e6-8455-f9e68e466694.PNG)

**Comment by gitwhatislove** [comment]
таск с кнопками новая есть
