### ISSUE TITLE
Форма заказа персонала

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/dremteam#65]
Количество рабочих часов (добавляется слово рабочих)

Дополнительные услуги заменить на Дополнительные опции (добавить в выпадалку - 
Трениг/репетиция)

![2016-07-28 15 17 51](https://cloud.githubusercontent.com/assets/18350195/17212121/2a01b4bc-54d6-11e6-94e6-e16d2846ea37.png)

**Comment by yuliyakislach** [comment]
2 слова пропускаешь, см. тз

**Comment by gitwhatislove** [comment]
не пролил, просто)

**Comment by yuliyakislach** [comment]
![2016-08-17 12 52 27](https://cloud.githubusercontent.com/assets/18350195/17732018/9e646c44-6478-11e6-9daa-6be40933a4a8.png)
