### ISSUE TITLE
Id

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/dremteam#68]
Вместо возраста на главной странице вывести поле id
![2016-07-28 16 03 30](https://cloud.githubusercontent.com/assets/18350195/17213255/448c1344-54dc-11e6-9b8e-71e3213f2df4.png)

**Comment by kkan** [comment]
![image](https://cloud.githubusercontent.com/assets/7046667/17269829/83785bfe-565c-11e6-97f9-418242982b68.png)
+
