### ISSUE TITLE
Сортировка по приоритету в каталоге

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/dremteam#69]

**Comment by kkan** [comment]
Оно и так сортируется: от большего к меньшему.

**Comment by yuliyakislach** [comment]
1й стоит -100
3я - 120

**Comment by kkan** [comment]
у меня норм
![image](https://cloud.githubusercontent.com/assets/7046667/17288284/fa11ea4c-57dc-11e6-8b68-0700a7ecc160.png)
![image](https://cloud.githubusercontent.com/assets/7046667/17288348/4c631866-57dd-11e6-9cd6-845123799973.png) ![image](https://cloud.githubusercontent.com/assets/7046667/17288297/09f00a8e-57dd-11e6-8860-e00a4ca32a60.png)![image](https://cloud.githubusercontent.com/assets/7046667/17288329/27bb3c82-57dd-11e6-8f92-ec5bb033a6cc.png)
