### ISSUE TITLE
Заменить фото

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/dremteam#70]
![2016-07-29 10 45 48](https://cloud.githubusercontent.com/assets/18350195/17241281/4af4dbf6-5579-11e6-90ac-17f7084d6834.png)

**Comment by gitwhatislove** [comment]
на какое ссылку?

**Comment by yuliyakislach** [comment]
http://dremteam-staging.dshop24.by/person/16 на главную вот этой и ссылка на нее же
